### ISSUE TITLE
Doesn't compile

### ISSUE THREAD

**Issue by mackie1908** [e-Spirit/FSDevTools#1]
Hi,

The last version I downloaded compiled and worked fine. I just downloaded a new version today and tried to compile but the build can't resolve the dependency for fs-license.jar. I don't have this and no idea how to get it. Can you provide some advice on how to resolve this. I have just upgraded to FirstSpirit 5.2.717 and I can't sync until I get this resolved.

Below is the output of the maven build following your instructions to compile the project.

[INFO] ------------------------------------------------------------------------
[INFO] Building FirstSpirit Development Tools Server Runner Module 1.0_DEV.123
[INFO] ------------------------------------------------------------------------
Downloading: https://repo.maven.apache.org/maven2/de/espirit/firstspirit/wrapper/3.5.12/wrapper-3.5.12.pom
[WARNING] The POM for de.espirit.firstspirit:wrapper:jar:3.5.12 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Command Line Interface API ......................... SUCCESS [ 58.472 s]
[INFO] FirstSpirit Development Tools Core ................. SUCCESS [ 14.686 s]
[INFO] Command Line Interface ............................. SUCCESS [ 59.241 s]
[INFO] FirstSpirit Development Tools Server Runner Module . FAILURE [  0.599 s]
[INFO] FirstSpirit Development Tools ...................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:13 min
[INFO] Finished at: 2017-04-07T16:39:26-04:00
[INFO] Final Memory: 62M/656M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project fsdevtools-serverrunner: Could not resolve dependencies for project com.espirit.moddev.fsdevtools:fsdevtools-serverrunner:jar:1.0_DEV.123: Failed to collect dependencies at de.espirit.firstspirit:fs-license:jar:[,5.2.717]: No versions available for de.espirit.firstspirit:fs-license:jar:[,5.2.717] within specified range -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :fsdevtools-serverrunner

Thanks,

**Comment by henczi-espirit** [comment]
Hi @mackie1908,
We apologize for the inconvenience. Our team is already working on this issue. You can try to use an older commit, or just wait until we have fixed the problem.

Thanks for reporting this issue.

Sincerely
your friendly e-Spirit developer

**Comment by mackie1908** [comment]
Hi,
What commit is best to use for the version of FirstSpirit I am running 5.2.717?

Thanks,

**Comment by henczi-espirit** [comment]
Hey @mackie1908,
You could try [this](https://www.google.com/url?q=https%3A%2F%2Fgithub.com%2Fe-Spirit%2FFSDevTools%2Ftree%2F48d1de952490de0b3342f28cf3dee28d57614694%23&sa=D&sntz=1&usg=AFQjCNGOhJqCVWFSZT8xzf5P9b6PDHEMyg).

Sincerely
your friendly e-Spirit developer

**Comment by zaplatynski-espirit** [comment]
Hi @mackie1908 ,

I pushed a quick fix so that you can compile without the module causing the trouble. Can you please confirm that it works for you that way?
Thank you in advance!

Regards,
Marian

**Comment by mackie1908** [comment]
Hi @zaplatynski-espirit ,

That has worked a treat and I have successfully imported and exported for the Version of FS 5.2.717. 

The only exception that was thrown was about a missing log4j.properties file but it still ran regardless. I will see if I can grab one from the repo directly but otherwsie that was the only thing that had an issue.

log4j:ERROR Could not read configuration file from URL [file:c:/Projects/FSDevTools/fs-cli/conf/log4j.properties].
java.io.FileNotFoundException: c:\Projects\FSDevTools\fs-cli\conf\log4j.properties (The system cannot find the file specified)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at java.io.FileInputStream.<init>(FileInputStream.java:93)
        at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
        at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
        at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:557)
        at org.apache.log4j.helpers.OptionConverter.selectAndConfigure(OptionConverter.java:526)
        at org.apache.log4j.LogManager.<clinit>(LogManager.java:127)
        at org.slf4j.impl.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:63)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:284)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:304)
        at com.espirit.moddev.cli.Cli.<clinit>(Cli.java:66)
log4j:ERROR Ignoring configuration file [file:c:/Projects/FSDevTools/fs-cli/conf/log4j.properties].
log4j:WARN No appenders could be found for logger (com.espirit.moddev.cli.reflection.CommandUtils).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

Thanks,

**Comment by zaplatynski-espirit** [comment]
Hi @mackie1908 

if you did not alter the content of the fs-cli.cmd?

It should work because we pass the the following to Java:
-Dlog4j.configuration=file:"%CLI_DIR%conf/log4j.properties"

The var CLI_DIR is calculated by
set CLI_DIR=%script_path:~0,-4%

So it should work regardless where you put it. By the way, I can not reproduce your error using the latest binary version from here.

Regards,
Marian
