### ISSUE TITLE
WIP Proposal: Export the projects FSM dependencies

### ISSUE THREAD

**Issue by cr4igo** [e-Spirit/FSDevTools#13]
**Work in Progress - this proposal is not yet completely defined, but you are very welcome to comment on it**

_Background of the proposal_:
When importing a project that has e.g. a custom input-component within its templates, an `import` command is not working. So you need to lookup the dependencies manually and install them by the current existing `module install` command beforehand.
As I recognized, that when you execute the fs-cli command `export root:templatestore projectproperty:ALL` and your current project depends on in my case a webapp-module, then a jar-file e.g. under "Global/Modules/WebApps/<Modulename>/<ModuleWebappName>/Webedit/lib/<modulejarname>.jar is being placed.

_Proposal_:
This brought up the question / idea, if there should be the possibility to export also complete FSMs. 

_Variant 1 "like install / uninstallation of modules, manual step for export one FSM"_:
Implement the possibility to export a module, so the .fsm file will be downloaded to the export directory.

_Variant 2 "optionally export used/required modules of the selected project"
Implement the possibility to export the module(s) that are required projects to do a sync / import command against an empty FirstSpirit server instance.

_Pros and Cons_:

Variant 1 "module export"-step:

- (+) can be soley used, so you dont have to look on the server module directory and export the files via ssh..
- (-) you need to list the modules manually

Variant "optionally export used/required modules of the selected project":

- (+) minimizing effort on fs-cli users side (you dont have to look up the dependencies manually)
- (+) errors when doing an import afterwards are minimized
- (+) you always have the latest versions of the FSMs when exporting the template-project
- (-) possible large files (FSMs) in the SCM (git, ..) repository --> e.g. use git-lfs for *.fsm to solve this

**Comment by hannespernpeintner** [comment]
Hey Markus,

thanks for your participation and the effort you already put into modeling the two possible solutions. We'll discuss this internally, thanks for your patience in advance :)

**Comment by hannespernpeintner** [comment]
Hi again,

I had a talk with Gerrit about the topic. The problem that we see here is, that probably unwanted dependencies are created between a project (content) and some modules. Release and deployment of modules is rather independent and stands for its own. What do you think about this problem?
