### ISSUE TITLE
Dependency FSTestTools could not be resolved

### ISSUE THREAD

**Issue by sosswa** [e-Spirit/FSDevTools#24]
Hi everyone,

I tried to build the FSDevTools to extend them. But a needed dependency, the "com.espirit.moddev.fstesttools", can not be resolved.
![image](https://user-images.githubusercontent.com/16187778/53396404-a0667600-39a4-11e9-94bd-415ca11c9d63.png)

As mentioned in this community post the fstesttools should be available on GitHub, but the link points to a 404 error.
https://community.e-spirit.com/community/developer/blog/2017/06/26/release-fs-test-tools-are-available-on-github-now
https://github.com/e-Spirit/FSTestTools

Please provide all needed dependencies to build and extend the FSDevTools as soon as possible, because we need them for a customer project.

I again ask for an official e-Spirit Maven repository so the build process would be **a lot** easier when we could just download the needed dependencies instead of building and installing it on our own!

Thanks
Sandro

**Comment by henczi-espirit** [comment]
Hi Sandro,
Thank you very much for opening this issue. We've recently removed the fstesttools GitHub project without noticing that there's this external dependency. We will fix this issue asap. We are sorry for any inconveniences this may have caused.
We'll release a bugfix very soon!
greetings,
Nico

**Comment by sosswa** [comment]
Hi @henczi-espirit,
do you have a timeline for a fix?

Thanks
Sandro

**Comment by henczi-espirit** [comment]
Hi @sosswa 
A timeline could be only given with an uncertain probability, 
(e.g. with a probability of 80% the fix will be released within the next 1-3 days)
But I can tell you, the fix is currently in our QA process, which means, 
the release is the next step. 

I also asked our QA to push this fix. 

I hope my answer could help you.
greetings,
Nico

**Comment by grossmueller-espirit** [comment]
Hi @sosswa 
the fix has been released yesterday. Please also note our comment to the community post you mentioned earlier on.

Regards,
Tanja
