### ISSUE TITLE
Project Name Parameter & Spaces CLI

### ISSUE THREAD

**Issue by frankbaus** [e-Spirit/FSDevTools#3]
Hi,

is there a Problem when using a project name with a space?

Example:

./fs-cli.sh -p 'Project Space' export -- root:templatestore

will lead to the following error:

com.espirit.moddev.cli.commands.help.UnknownCommandException: fs-cli Space export root:templatestore

Storing the name in an environment variable is working fine.

**Comment by mikula-espirit** [comment]
Hey Frank,

I tried the command and you are right, there seems to be an issue with single quotes: try double quotes instead. 
`./fs-cli.sh -p "Project Space" export -- root:templatestore`
But we'll look into this.

**Comment by frankbaus** [comment]
Hi,

its the same with double quotes for me ;(
Thanks for the reply though,

Frank

**Comment by mikula-espirit** [comment]
as i said, we'll take a look at it :)

**Comment by hannespernpeintner** [comment]
Hi Frank,

which version of the tool do you use? Are you sure, that you really have the latest shell files (located in bin folder)? I know that there were issues some long long time ago, that were fixed for all operating systems. We had a small test with linux and everything worked as expected. Could you give us additional information about your setup? And could you please build the tools from scratch, just to be sure that your issue doesn't source from customizations you did somehow?

Thanks for your patience,
Hannes

**Comment by frankbaus** [comment]
Hi Hannes,

these are the Version Numbers:

fs-cli version 2.0.539 / git hash a942733b5772f6fdad70a8ccf1ac8159b146a811
Build for FirstSpirit version 5.2.802
Using FirstSpirit Access API version 5.2.802.75920

Greetings,

Frank

**Comment by hannespernpeintner** [comment]
I'm sorry, but we can't reproduce your error. Could you please ensure that you use the latest release of the tool - and especially unmodified shell files (the ones we deliver in the bin folder)?

**Comment by frankbaus** [comment]
This is working for me now
