### ISSUE TITLE
Update dependency com.github.rvesse.airline to latest version

### ISSUE THREAD

**Issue by Christian-Brockmann** [e-Spirit/FSDevTools#32]
Hi, 

i am currently creating a new command for the FSDevTools, which will be added to the already available commands via a jar.
I want to use and overwrite a typeConverterProvider for easier reading via the Option Annotation. 
Unfortunately the FSDevTools uses the version 2.1.1. of com.github.rvesse.airline and with this version i am not able to override the typedConverter. 
When i am trying to create a custom converter and run the command, always the DefaultTypeConverter is used. 
So could you please test if the version of com.github.rvesse.airline can be updated?

Thank you and best regards
Christian

**Comment by GeMoschen** [comment]
Hi Christian,
I will close this ticket here because we are currently reviewing your pull-request and we are also updating other outdated libraries in this step.

Thanks for your report and your pull-request :)

**Comment by kafmann-e-spirit** [comment]
Hi Christian,
I will close this ticket here because we are currently reviewing your pull-request and we are also updating other outdated libraries in this step.

Thanks for your report and your pull-request :)
