### ISSUE TITLE
Export workflow permissions

### ISSUE THREAD

**Issue by m-kotowski** [e-Spirit/FSDevTools#40]
Using the basic workflows, we allowed "everybody" to use them by selecting "all" in the workflow permissions tab of the content (green) and structure (blue) roots.

After exporting the project and importing it again, the selected "all" is gone. As a result, for example, the delete workflow is not available anymore.

It would be great, if the workflow permissions would be exported and/or successfully imported.

![export-workflow-permissions](https://user-images.githubusercontent.com/16794506/71877860-7cc69d00-312a-11ea-90e9-98b15d0e2f33.png)

**Comment by kafmann-e-spirit** [comment]
Hey Michael,
is just want to inform you that this feature has been released with [Release 3.0.0](https://github.com/e-Spirit/FSDevTools/releases/tag/3.0.0) - ([Changelog](https://github.com/e-Spirit/FSDevTools/blob/master/RELEASENOTES.md#version-300)).

Please be aware that at least FirstSpirit 5.2.2107 is required.

Thanks for your contribution and patience!
