### ISSUE TITLE
Using the CLI to track templates changes in git - problem with new templates

### ISSUE THREAD

**Issue by grouchal** [e-Spirit/FSDevTools#41]
We use the CLI tool so that we can keep all the temples from a project in git.

For each feature we work in different branches in git and then use the CLI to import changes from master and export changes relevant for the branch. Each developer has a local server and needs to use the CLI to load the templates from different branches into their local dev project. 

This works well until we have new objects (templates, media or similar) that come from another branch and need to be created in firstspirit.

We really require that we can import new objects too, is it possible to explain what the problems are with creating new objects?

We would happily invest some development time in adding the functionality to the CLI to do this if we could be guided a bit in where the changes need to be made.

**Comment by m-kotowski** [comment]
Hi @grouchal. Perhaps the import option `-lm *:CREATE_NEW` helps!?

**Comment by grouchal** [comment]
@m-kotowski sorry for the delay in answering but `-lm *:CREATE_NEW` only seems to work for the data layer and doesn't create new templates etc which is what would be of interest for us.

We'd really like to get this working - if anyone can point to how we could update the CLI to support this we would be interested in getting implemented, and happy to create a pull request for review.

We are not sure if it not working is a restriction in the CLI code or a restriction in the firstspirit server.

We see this as crucial to fully automating the versioning of templates and working on different machines using the CLI.
