### ISSUE TITLE
Add command to run schedules

### ISSUE THREAD

**Issue by m-kotowski** [e-Spirit/FSDevTools#42]
Hi. I did not find any command to run schedules from the command line. It would be great to have such a feature, which also shows the log output allowing a faster debugging in case of problems. Currently, I have to run a schedule, wait for its end, open the log, scroll up/down to find yellow/red marked lines, etc. Would be helpful to have it on the command line to use for example grep and other tools for faster analysis.

Any questions?

**Comment by kafmann-e-spirit** [comment]
Hey Michael,
we are currently planning to implement a command to run schedules (server & project) any time soon.

Thanks for your question :)

**Comment by kafmann-e-spirit** [comment]
Hey @m-kotowski ,
I just want to inform you that the latest Release (2.5.10) contains the "schedule entry" feature :)

See this [commit ](https://github.com/e-Spirit/FSDevTools/commit/9e3712b49e619282530293ddd51218e3284fcd84) for implementation details.

Short description:
* added command "schedule list"
* added command "schedule start"

Both commands can be used server-side and with a project name.

**Example for _schedule list:**

Serverwide: 
_fs-cli.exe -p schedule list_

Project: 
_fs-cli.exe -p "my ProjectName" schedule list_

For further information about the command syntax, please use _fs-cli.exe help schedule_
