### ISSUE TITLE
Extend schedule run command for CI Pipeline

### ISSUE THREAD

**Issue by th1nkgr33n** [e-Spirit/FSDevTools#44]
Hey folks,

first of all thank for that implementation to run schedule entries.

But in the end that current feature set doesn't match my needs.
I want to run schedule entries with the fs-cli from inside a ci pipeline.
For that it is necessary to have control whether a schedule run was successfully or it failed.
And if it failed I need much more details on the kind of errors to decide if I have to exit the whole pipeline.

Currently there is only a short response that the run was successful and nothing else.

Are there plans on your side to implement such kind of extension or is the way to go to do it by my self and open a PullRequest which you can accept or not?

Kind Regards
Olli

**Comment by kafmann-e-spirit** [comment]
Hi @th1nkgr33n ,

If the execution of a schedule run fails, the CLI will return with exit code 1. So in your case: simply grab the exit code of the executed CLI and handle it properly :)

Anyway, if this doesn't help you: feel free to open a PR :)

Regards,
Christian

**Comment by th1nkgr33n** [comment]
Hey Christian thanks for the quick response,

> If the execution of a schedule run fails, the CLI will return with exit code 1

unfortunately this is not quite true, I attached a screenshot where you can see that the command returns successful, but in the generation log exists 1 error and 1 warn.

As I examine the source code, there is also no kind of checking for generation state. Just if overall an exception was thrown in the code itself.

On other projects, we analyse the ScheduleEntryControl.getState() results to validate that.

![Bildschirmfoto 2020-06-12 um 13 43 22](https://user-images.githubusercontent.com/7330927/84499523-10406300-acb3-11ea-9ffe-55d4785238ea.png)

But then I will go with the PR option. Just wanted to be safe that it is not in your Backlog / Roadmap and run into something that will be added by you anyway in near future.

Regards, 
Olli

**Comment by kafmann-e-spirit** [comment]
Hey @th1nkgr33n ,

thanks for your clarification. Seeing your screenshots and descriptions, we might have missed something there. We will take a look at this to check if there might be a bug.

In my opinionen, the correct behaviour should be an exit code != 0. I think that we are going fix this behaviour if this is not the case.

So thanks for your report :)

Regards,
Christian

**Comment by kafmann-e-spirit** [comment]
Hey @th1nkgr33n ,

I have taken a look at the code and can confirm that the current behaviour does not throw an Exception if the state of the schedule entry is not successful.

We will fix this bug as soon as possible, thanks once again :)

**Comment by kafmann-e-spirit** [comment]
Hey @th1nkgr33n ,
I just want to inform you that we fixed this bug with [Release 2.6.2](https://github.com/e-Spirit/FSDevTools/releases/tag/2.6.2).

Thanks for your contribution!
