### ISSUE TITLE
Mention official documentation in readme 

### ISSUE THREAD

**Issue by MiniDigger** [e-Spirit/FSDevTools#46]
hey, thanks for making this project available, I hope that it will greatly improves our workflows.
I first had issues getting started, before I found via random googling, that you actually have good documentation for this. 
I would recommend to link the documentation in the readme of this project, so its easier to find!
https://docs.e-spirit.com/odfs/edocs/sync/introduction/index.html

**Comment by kafmann-e-spirit** [comment]
Hey @MiniDigger ,
I just want to inform you that we added a link with Release 2.6.10.

Thanks for your contribution!
