### ISSUE TITLE
Enhancement/Proposal: Entities of all datasources within a project cannot be easily exported

### ISSUE THREAD

**Issue by cr4igo** [e-Spirit/FSDevTools#5]
Currently you need to repeat the command per one datasource, so you end like:

`export entities:products entities:categories entities:... ...`

There should be a more efficient and comfortable way to export all entities and transfer them with the complete content to another stage (e.g. export from PROD and import to DEV).

There are several possible ways we could achieve this:

* use the syntax as it exists for other elements like 
`export entities:ALL`
and extend the current existing export entities:<content2_id> logic.

* implement a more general cmd function "execute_script" which executes a Script/Class that must exist inside the current server as FSM/project script and do a subprocess call for generating the cmd arguments of the "export" call automatically

* or by a custom command like "export_all_entities"

* the above logics could also use an e.g. configurable regular expression, so you can configure by the uid/uid-path of the content2-element if it should be exported or not.

**Comment by hannespernpeintner** [comment]
Hi :)

Thank you for your proposal - I'm afraid that the export of all entities is something that we don't want to officially support or encourage with the external sync feature. That's the reason why export entities:ALL is not implemented by us on purpose.

Regards,
Hannes
