### ISSUE TITLE
How about just a groovyScript that can be executed generically via the fs-cli ?

### ISSUE THREAD

**Issue by cr4igo** [e-Spirit/FSDevTools#51]
Some years ago I implemented an easy way to just execute a bunch of groovy script files. Give it a list of json parameters. Thats it.
With that solution we are able to run one or more scriptfunctionality without adapting the fs-cli for each functionality.
So it is perfect for the fast pace we need to adapt and change things in our daily business. Would also remove some effords on the e-Spirit side as well (codereview, adapting to newer fs-cli versions, ...).
We could additionally do a separate repository - for example via the ESUG github group for just sharing our "best-of-breed" scripts. So just some smaller scripts for basic tasks.

What do you think about it @kafmann-e-spirit , @boesebeck-espirit  ? 

`./fs-cli-wrapper groovyscript run --scriptURI=file:///usr/local/customer/workdir/groovyscripts/dosomethingawesome.groovy --scriptParameters "$(./jq -c '.' < scriptparameters.json)"`
[@see code](https://github.com/cr4igo/FSDevTools/blob/master/fsdevtools-cli/src/main/java/com/espirit/moddev/cli/commands/groovyscript/RunGroovyScriptCommand.java)
I use the jq command to read the json in an acceptable escaped way for the json :D. This is not as easy as you first think. Maybe I will also implement a direct parameter to just give like the scriptURI another URI for the json parameters. Could also be yaml parameters as maybe some would like to just use yaml instead of json.

The groovyscript gets the 'fsConnection', 'fsContext' and 'scriptParameters' injected. Then you can start from there to use FirstSpiritAgents, Services and so on, just for perfectly customizable processes. We just used it for e.g. to load javascript/css/.. to the mediastore, release it recursively afterwards, manipulating maintenance tasks and executing them afterwards, etc. while skipping the "customize, build, release etc. stuff for the 'customized' fs-cli itself". Also if it would be a basic functionality we would not have to merge our custom fs-cli with the official one on a regular basis.

Thank you for your advice and time!

Here you can find the changes for the releases 4.0.0 and 2.6.10 to check it out: [https://github.com/e-Spirit-Usergroup/FSDevTools/releases/](https://github.com/e-Spirit-Usergroup/FSDevTools/releases/)

**Comment by kafmann-e-spirit** [comment]
Hey @cr4igo ,
I just want to inform you that your request has been approved and the feature will be implemented with the next release.

The new commands will be...
- script run  --scriptFile|-sf <PATH> [--scriptType|-sf=BEANSHELL(DEFAULT)|GROOVY]
  - executes the given script with the given engine (default=BEANSHELL)
- script parse --scriptFile|-sf <PATH> [--scriptType|-sf=BEANSHELL(DEFAULT)|GROOVY]
  - parses the given script with the given engine (default=BEANSHELL) but does **not** execute it 


The context parameters will be consistent to the already known FirstSpirit ScriptContexts and will feature a "context"-parameter that is based on a [ProjectScriptContext (docs.espirit.com)](https://docs.e-spirit.com/odfs/access/de/espirit/firstspirit/access/project/ProjectScriptContext.html). The project is optional and may be null, like always in the CLI if you do not enter the project name as a global variable.
